In [6]:
import numpy as np

In [3]:
a = np.array([[10,20,30,40],[50,60,70,80]])

In [4]:
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [5]:
a.shape

(2, 4)

In [7]:
b = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])

In [8]:
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [9]:
b.shape

(2, 3, 4)

In [11]:
print(a.ndim)

2


In [12]:
a = np.array([[0,1,2],[3,4,5]])

In [13]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
a[0,0]

0

In [15]:
a[-1,-1]

5

In [16]:
a = np.array([[0,1,2,3],[4,5,6,7]])

In [17]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
a[0,:]  #첫번째 raw의 모든 column

array([0, 1, 2, 3])

In [23]:
a[:,1]   #모든 raw의 두번째 column

array([1, 5])

In [24]:
a[:,:]  #모든 raw의 모든 column

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
a[:2,:2]  #0번째 raw 1번째 raw까지 0번째 column부터 1번쨰 column까지

array([[0, 1],
       [4, 5]])

In [27]:
#슬라이싱도 range와 비슷하게 

In [28]:
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

In [29]:
print(m[1,2])
print(m[-1,-1])
print(m[1,1:3])
print(m[1:3,2])
print(m[:2,3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [30]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [31]:
idx = np.array([True, False, True, False,True, False,True, False,True, False,])

In [32]:
a[idx]

array([0, 2, 4, 6, 8])

In [33]:
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [34]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [35]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [36]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,2,4,6,8])
a[idx]

array([11, 33, 55, 77, 99])

In [37]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
a[:,[True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [41]:
a[[2,0,1],:]  #3번째 raw부터 0번째 전까지 1씩 증가 # 모든 column

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [42]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [43]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [44]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [47]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

In [53]:
x = np.array([1,2,3])
x.dtype

dtype('int32')

In [58]:
g = np.empty((4,3))
g

array([[1.24794201e-311, 2.81617418e-322, 0.00000000e+000],
       [0.00000000e+000, 1.16709769e-312, 6.82116729e-043],
       [5.64042459e-091, 5.49167846e+174, 1.00511991e-047],
       [9.14764895e-043, 6.48224659e+170, 4.93432906e+257]])

In [59]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(3,22,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [61]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [65]:
A.T  #반환하지 않는다

array([[1, 4],
       [2, 5],
       [3, 6]])

In [66]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
a.reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [70]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [71]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [72]:
x = np.arange(1,10001)
y = np.arange(10001, 20001)

In [73]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: total: 0 ns
Wall time: 4.01 ms


In [74]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [75]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [76]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [77]:
a == b

array([False,  True, False,  True])

In [78]:
c = np.array([1,2,3,4])
np.all(a == b)

False

In [79]:
np.all(a == c)

True

In [80]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [83]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [84]:
x + y

array([1., 2., 3., 4., 5.])

In [85]:
#연습문제
import numpy as np
np.__version__

'1.23.1'

In [86]:
a = np.array([0,0,0,0,0,0,0,0,0,0])
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
a.shape

(10,)

In [89]:
b = np.zeros(10)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [90]:
b_1 = np.full(10,0)
b_1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [99]:
n_arr = np.array([1,2,3,4,5,6,7,8,9,10], dtype = np.int64)

In [100]:
n_arr.itemsize

8

In [104]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
a = a[::-1]
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [106]:
a = a.reshape(2,5)
a

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [107]:
a = a.reshape(5,2)
a

array([[10,  9],
       [ 8,  7],
       [ 6,  5],
       [ 4,  3],
       [ 2,  1]])

In [108]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [111]:
np.random.seed(2)
a = np.random.random(10)
print(a.max())
print(a.min())
print(a.mean())

0.6192709663506637
0.025926231827891333
0.358801017672414


In [120]:
n = int(input("n : "))
arr_1 = np.full((n,n),0)
for i in range(n):
    for j in range(n):
        if (i+j)%2 == 0:
            arr_1[i,j] = 1
print(arr_1)

n :  3


[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [124]:
n = int(input("n : "))
arr_2 = np.full((n,n), 0)
for i in range(n):
    arr_2[i,i] = i+1
print(arr_2)

n :  10


[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


In [125]:
n = int(input("n : "))
arr_3 = np.full((n,n),1)
arr_3[1:-1, 1:-1] = 0
print(arr_3)

n :  10


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [128]:
n = int(input("n : "))
arr_4 = np.full((n,n),1)
arr_4[1:-1,1:-1] = 0
arr_4 = (arr_4-1)*(-1)
print(arr_4)

n :  10


[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [52]:
a = np.arange(0,81,10)
b = np.arange(0,21,20)

In [53]:
print(a)
print(b)

[ 0 10 20 30 40 50 60 70 80]
[ 0 20]


In [61]:
T_or_F = np.full(a.shape, False)  # 배열로 구하는 법
idx = 0
for i in a:
    if i in b:
        T_or_F[idx] = True
    idx += 1
print(T_or_F)
print(type(T_or_F))

[ True False  True False False False False False False]
<class 'numpy.ndarray'>


In [60]:
list_a = []  #리스트로 구하는 법
for i in a:
    if i in b:
        list_a.append(True)
    else:
        list_a.append(False)
print(list_a)
print(type(list_a))  

[True, False, True, False, False, False, False, False, False]
<class 'list'>


In [63]:
x = np.array([[10,20,40,60],[10,20,40,40]])

In [64]:
a, b = np.unique(x.ravel(), return_counts = True)

In [70]:
a  # x 배열에서 중복없이 추출함

array([10, 20, 40, 60])

In [71]:
b   # x배열에서 각 요소별 갯수

array([2, 2, 3, 1], dtype=int64)

In [69]:
for i , j in zip(a,b):
    print(i,j)

10 2
20 2
40 3
60 1


In [72]:
y = np.array([[80,120,40], [60,80,120],[40,40,40]])

In [74]:
a,b = np.unique(y.flatten(), return_counts = True)
for i, j in zip(a,b):
    print(i,j)

40 4
60 1
80 2
120 2


In [75]:
a = np.array([0,10,20,40,60,80])
b = np.array([0,20])

In [79]:
c = np.empty(0)   #빈 배열 만들기

In [81]:
for i in a:
    if i not in b:
        c = np.append(c,i)
print(c)

[10. 40. 60. 80.]


In [83]:
d = np.setdiff1d(a,b)   #차집합을 구하는 np.setdiff1d
print(d)

[10 40 60 80]


In [87]:
n = int(input("n : "))
arr_1 = np.full((n,n),0)
for i in range(n):
    arr_1[i,i] = 1
    arr_1[i,n-i-1] = 1
print(arr_1)

n :  10


[[1 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 1]]


In [93]:
n = int(input("n : "))
arr_2 = np.full((n,n),0)
for i in range(n):
    arr_2[i,:i+1] =1
print(arr_2)

n :  5


[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


In [94]:
arr_2.sum()

15

In [95]:
arr_2.sum(axis = 0)

array([5, 4, 3, 2, 1])

In [96]:
arr_2.sum(axis = 1)

array([1, 2, 3, 4, 5])

In [148]:
a = np.array([[0,1,2],[3,4,5],[0,2,4],[6,8,10]])
b = np.array([[0,1,2,0,2,4],[3,4,5,6,8,10]])

In [149]:
a   #배열의 형태를 보고 자르기

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  2,  4],
       [ 6,  8, 10]])

In [150]:
a_1 = a[0:2,:]   #배열을 두개로 자르기
a_2 = a[2:,:]
print(a_1)
print(a_2)

[[0 1 2]
 [3 4 5]]
[[ 0  2  4]
 [ 6  8 10]]


In [151]:
a = np.concatenate((a_1, a_2), axis = 1)  #column 끼리 합치는 방법
a

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10]])